In [3]:
import numpy as np

In [6]:
data = np.random.uniform(-100, 100, size=1000)
np.save("f1.npy", data)

In [7]:
test_func_bound = {
    1:[-100, 100],
    2:[-100, 100],
    3:[-100, 100],
    4:[-5, 5],
    5:[-600, 600],
    6:[-32, 32],
    7:[0, 0],
}

for i in range(1, 7):
    bound = test_func_bound[i]
    data = np.random.uniform(bound[0], bound[1], size=1000)
    np.save("f%d.npy" % i, data)

In [8]:
np.pi

3.141592653589793

In [9]:
a = np.ones(5)

In [11]:
tmp = a*a - 10 * np.cos(2*np.pi*a) + 10

In [12]:
tmp

array([1., 1., 1., 1., 1.])

In [13]:
np.sum(tmp)

5.0

In [15]:
np.sum(a*a - 10 * np.cos(2*np.pi*a)) + 10 * 5

5.0

In [16]:
np.multiply(a, a)

array([1., 1., 1., 1., 1.])

In [17]:
np.cos(1)

0.5403023058681398

In [18]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.sqrt(1)

1.0

In [20]:
np.e

2.718281828459045